# Generated by Django 5.2.11 on 2026-02-19 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('PM', 'Project Manager'), ('DEV', 'Developer'), ('QA', 'QA Tester'), ('MGR', 'Manager'), ('AP', 'Approver'), ('TL', 'Test Lead')], max_length=10),
        ),
    ]
