sonar.projectKey=AL-PMT-BACKEND
sonar.projectName=AL PMT BACKEND
sonar.projectVersion=1.0

sonar.host.url=http://localhost:9000
sonar.token=sqp_271c92b2b464ebaa5f033684269120da07617607

sonar.sources=.
sonar.language=py
sonar.python.version=3.11

# Exclude virtual env and migrations
sonar.exclusions=venv/**,**/migrations/**,**/__pycache__/**,**/tests/**

sonar.sourceEncoding=UTF-8