# Generated by Django 5.2.11 on 2026-02-16 08:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_initial'),
        ('sprints', '0001_initial'),
        ('userstories', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='userstory',
            index=models.Index(fields=['project'], name='userstories_project_f36773_idx'),
        ),
        migrations.AddIndex(
            model_name='userstory',
            index=models.Index(fields=['sprint'], name='userstories_sprint__638836_idx'),
        ),
        migrations.AddIndex(
            model_name='userstory',
            index=models.Index(fields=['status'], name='userstories_status_b76565_idx'),
        ),
    ]
