# Generated by Django 5.2.11 on 2026-02-08 08:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userstories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userstory',
            name='points',
            field=models.CharField(default='?', max_length=10),
        ),
        migrations.AddField(
            model_name='userstory',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Ready', 'Ready'), ('In Progress', 'In Progress'), ('Done', 'Done')], default='New', max_length=20),
        ),
    ]
