# Generated by Django 5.2.11 on 2026-02-08 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userstories', '0002_userstory_created_at_userstory_points_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstory',
            name='ref',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
