# Generated by Django 5.2.11 on 2026-02-08 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_description'),
        ('sprints', '0001_initial'),
        ('userstories', '0003_userstory_ref'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userstory',
            options={'ordering': ['ref']},
        ),
        migrations.AddField(
            model_name='userstory',
            name='sprint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='userstories', to='sprints.sprint'),
        ),
        migrations.AlterField(
            model_name='userstory',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userstories', to='projects.project'),
        ),
        migrations.AlterField(
            model_name='userstory',
            name='ref',
            field=models.PositiveIntegerField(),
        ),
    ]
