# Generated by Django 5.2.11 on 2026-02-08 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_description'),
        ('sprints', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sprint',
            options={},
        ),
        migrations.AlterField(
            model_name='sprint',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project'),
        ),
    ]
