# Generated by Django 5.2.11 on 2026-03-16 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_task_tasks_task_user_st_ff01b6_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='actual_hours',
        ),
    ]
